export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODRUCT = 'REMOVE_PRODRUCT';

//Products Reducer
export const ADD_PAGE = 'ADD_PAGE';
export const FILTER_BASICS = 'FILTER_BASICS';
export const FILTER_BASICS_REMOVED = 'FILTER_BASICS_REMOVED';
export const FILTER_BASICS_START = 'FILTER_BASICS_START';
export const FILTER_BASICS_SUCCESS = 'FILTER_BASICS_SUCCESS';
export const FILTER_BASICS_FAIL = 'FILTER_BASICS_FAIL';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';