//Cart Reducer
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODRUCT = 'REMOVE_PRODRUCT';

//Products Reducer
export const ADD_PAGE = 'ADD_PAGE';
export const FILTER_BASICS = 'FILTER_BASICS';
export const FILTER_BASICS_REMOVED = 'FILTER_BASICS_REMOVED';
export const FILTER_SORT = 'FILTER_SORT';
export const FILTER_SORT_REMOVED = 'FILTER_SORT_REMOVED';
export const FILTER_RANGE_PRICES = 'FILTER_RANGE_PRICES'; 

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
